# Generated by Django 4.2.1 on 2023-05-31 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_spec', models.CharField(max_length=255)),
                ('doc_image', models.ImageField(upload_to='contact')),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('dep_name', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
            ],
        ),
    ]
