# Generated by Django 4.2.1 on 2023-05-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='doc_image',
            field=models.ImageField(upload_to='contact'),
        ),
    ]
